### ISSUE TITLE
import_py3package_from_pypi does not work anymore

### ISSUE THREAD

**Issue by bmasciarelli** [azureautomation/runbooks#90]
It seems there has been a change on the python 3 environment used by Automation.

Last week I used **import_py3package_from_pypi** for importing **azure-identity** and it worked fine, now it doesn't. It fails with:
`Traceback (most recent call last): File "C:\WPy64-3800\python-3.8.0.amd64\lib\automationassets.py", line 155, in _issue_request response = urllib.request.urlopen(request) File "C:\WPy64-3800\python-3.8.0.amd64\lib\urllib\request.py", line 222, in urlopen return opener.open(url, data, timeout) File "C:\WPy64-3800\python-3.8.0.amd64\lib\urllib\request.py", line 531, in open response = meth(req, response) File "C:\WPy64-3800\python-3.8.0.amd64\lib\urllib\request.py", line 640, in http_response response = self.parent.error( File "C:\WPy64-3800\python-3.8.0.amd64\lib\urllib\request.py", line 569, in error return self._call_chain(*args) File "C:\WPy64-3800\python-3.8.0.amd64\lib\urllib\request.py", line 502, in _call_chain result = func(*args) File "C:\WPy64-3800\python-3.8.0.amd64\lib\urllib\request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp)urllib.error.HTTPError: HTTP Error 404: Not FoundDuring handling of the above exception, another exception occurred:Traceback (most recent call last): File "C:\Temp\rwkbzl2s.0mz\fc3f4da0-b392-474b-8049-8403db2e0522", line 127, in <module> token = get_automation_runas_token() File "C:\Temp\rwkbzl2s.0mz\fc3f4da0-b392-474b-8049-8403db2e0522", line 40, in get_automation_runas_token cert = automationassets.get_automation_certificate("AzureRunAsCertificate") File "C:\WPy64-3800\python-3.8.0.amd64\lib\automationassets.py", line 237, in get_automation_certificate certificate = _client.get_certificate_asset(name) File "C:\WPy64-3800\python-3.8.0.amd64\lib\automationassets.py", line 191, in get_certificate_asset return self._issue_request(url, self._GET) File "C:\WPy64-3800\python-3.8.0.amd64\lib\automationassets.py", line 158, in _issue_request raise AutomationAssetNotFound()automationassets.AutomationAssetNotFound`

**Comment by AkechiShiro** [comment]
@bmasciarelli Is this issue still relevant, today ?

**Comment by bmasciarelli** [comment]
Hey @AkechiShiro, no, it seems it was fixed automatically a couple of weeks later.

**Comment by timwilke** [comment]
Hi @AkechiShiro, today I experienced the same error as @bmasciarelli. Something doesn't seem to be working right yet.

**Comment by cpereir1** [comment]
Hello, all! It is happening to me today. So I guess not fully solved?
